name: bmi_calculator
description: a Body Mass Index Calculator inspired by the beautiful designs made by Ruben Vaalt.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Solway
      fonts:
          - asset: fonts/Solway-Regular.ttf

    - family: Tomorrow
      fonts:
        - asset: fonts/Tomorrow-Regular.ttf


    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf




